version: '3.3'

services:
  postgres:
    image: postgres:latest
    container_name: auth_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - auth_db:/var/lib/postgresql/data

volumes:
  auth_db:
    driver: local